name: Staging Phase

on:
  push:
    branches:
      - 'master'

env:
  DOCKER_IMAGE_REPOSITORY_NAME: atix-v2
  DOCKER_IMAGE_TAG_NAME: booking-be-dev-v2 
  DOCKER_SERVICE_NAME: atix-booking-be-dev-v2 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout Repository
      uses: actions/checkout@v2
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        build-args: |
          USERNAME_GITHUB=${{ secrets.USERNAME_GITHUB }}
          TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_REPOSITORY_NAME }}:${{ env.DOCKER_IMAGE_TAG_NAME }}-${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_REPOSITORY_NAME }}:${{ env.DOCKER_IMAGE_TAG_NAME }}-latest
    - 
      name: Executing remote command using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd deploy-finns/dev
          docker compose rm -sf ${{ env.DOCKER_SERVICE_NAME }}
          docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_REPOSITORY_NAME }}:${{ env.DOCKER_IMAGE_TAG_NAME }}-latest
          docker compose up -d ${{ env.DOCKER_SERVICE_NAME }}